### ISSUE TITLE
32x32 matrix 1/8 scan

### ISSUE THREAD

**Issue by AST-esp-rasp** [hzeller/rpi-matrix-pixelpusher#13]
Hello what settings can i use for a 32x32 matrix 1/8 scan?
where is the coding made for this?
or can i use the option -r 16 -c 2 for this?

**Comment by hzeller** [comment]
You essentially need to write a CanvasTransformer, and run with -r16 -c2.

(I don't have a 1/8 scan panel to test, otherwise I'd included that already)

**Comment by AST-esp-rasp** [comment]
Hello Henner,
I will give this a try later.
Since i have for my actual project 2x 32x64 panels with 1/16 scan.
These work without any problem. 
The project i'm working on is an archery competition clock.(indoor)
The countdown is shown on a remote display.(rpi connected with the displays) For the generation of the graphics i'm using processing on a PC.
I can post a YouTube link once i'm ready with it.
Regarding the 32x32 panels i can send you one for testing?
The manufacturer from China just told me that all their P5 outdoor panels work with 1/8 scan.
But i will need this back since it is assigned to the outdoor clock project.

Kind regards
Andreas Stolpe

Von meinem iPad gesendet

**Comment by hzeller** [comment]
Nice idea with the scoreboard.

Yes, all outdoor panels are 1:8, because that allows to get them much brighter (they will probably use roughly twice as much power).

Sending a 1:8 panel to San Francisco and back is probably some hassle, but if you have a link to the panel you bought, then I might have a look. Work on the library is only as time permits, so I can't really promise anything.

You might want to read the thread on the rpi-rgb-led-matrix  https://github.com/hzeller/rpi-rgb-led-matrix/issues/66 where people work on figuring out the pixel mapping they see on their boards.

**Comment by hzeller** [comment]
BTW, these multiplex mappings are now natively supported in the library with the `--led-multiplexing` option.
