### ISSUE TITLE
Using LED Labs?

### ISSUE THREAD

**Issue by snap2222** [hzeller/rpi-matrix-pixelpusher#8]
An important part of my project depends on the use of LED Labs to control my 32x192 pixel matrix. Have others had success in using it and would there be any issues you are aware of?

Thanks again.

**Comment by hzeller** [comment]
People have used LED Labs with this implementation before. The only problem is, that iOS limits the UDP packet size to 8kB or so, so setting the UDP size in the `rpi-matrix-pixelpusher` program larger than that might not work. The defaults are 1460, so that should be safe.
(You can change the size with the `-u` option.)

**Comment by snap2222** [comment]
Thank you for your response, I'm excited to find this solution. If may ask one more question?   Does the RPi do the work of PP? Meaning I won't require to use a PP. Is that correct?

**Comment by hzeller** [comment]
Yes, the Raspberry Pi behaves like a PixelPusher, so whatever you send to a PP typically should work with this solution.
